package com.example.beautysalonrestspring.model.enums;

public enum TimeSlotType {
    NINE_TO_TEN,TEN_TO_ELEVEN,ELEVEN_TO_TWELVE,
    TWELVE_TO_THIRTEEN,THIRTEEN_TO_FOURTEEN,FOURTEEN_TO_FIFTEEN,
    FIFTEEN_TO_SIXTEEN,SIXTEEN_TO_SEVENTEEN,SEVENTEEN_TO_EIGHTEEN
}
